### ISSUE TITLE
Image noise problem

### ISSUE THREAD

**Issue by GGyan** [kumar-shridhar/PyTorch-BayesianCNN#10]
when I use the Bayesian convolution neural network to process image problems, the output image has noise. Do you know why this is?

**Comment by kumar-shridhar** [comment]
Hi @GGyan, 
Can you please provide more information? Like what file you ran on what dataset and where was the noise?

**Comment by GGyan** [comment]
I am very happy with your reply,When I use Bayesian convolution neural networks, I define a convolution layer and then input the dataset for training. After finishing the training, I input a picture and test it. The result showed that the picture produced noise. I don't know what caused the noise and hope to remove the noise. My dataset: https://sites.google.com/site/boyilics/website-builder/project-page. Because I am studying image defogging, my dataset is divided into two parts: artificial synthetic haze image and the original no-haze image. The results of my test are shown below: 


On 5/15/2019 15:36，Kumar Shridhar<notifications@github.com> wrote：

Hi @GGyan,
Can you please provide more information? Like what file you ran on what dataset and where was the noise?

**Comment by GGyan** [comment]
![man](https://user-images.githubusercontent.com/50450546/57774803-0fef3480-774e-11e9-9174-5fd60792b56e.png)
![noiseman](https://user-images.githubusercontent.com/50450546/57774828-21d0d780-774e-11e9-8462-752e819d56fb.png)

**Comment by GGyan** [comment]
[http://chuantu.xyz/t6/702/1557922583x2362407012.png](url)
[http://chuantu.xyz/t6/702/1557922656x2362407012.png](url)

**Comment by GGyan** [comment]
![man](https://user-images.githubusercontent.com/50450546/57775248-2a75dd80-774f-11e9-9c7a-16e96114a71c.png)
![noiseman](https://user-images.githubusercontent.com/50450546/57775253-2d70ce00-774f-11e9-98d4-3376d599082c.png)

**Comment by kumar-shridhar** [comment]
Did you use the super resolution code for this? I think the result is interesting and maybe due to the latest changes in the Bayesian distribution layer, the noise is added due to an inefficient sampling method use. The results should be fixed with the code update that I will push soon (in 10 days). Thank you for addressing the issue.

**Comment by GGyan** [comment]
Thank you for your timely answer.

**Comment by kumar-shridhar** [comment]
Hi @GGyan,
can you try to run your code now and see if anything changes.
