### ISSUE TITLE
what is the reasoning behind α*μ² BCNN variance?

### ISSUE THREAD

**Issue by mrivar** [kumar-shridhar/PyTorch-BayesianCNN#12]
Hi, I've been following your work for a while. In your paper, you define the variance in BCNN filters as `α*μ²`  although in your recent change you get rid of this, having a general standard deviation (the parameter being `conv_qw_std`). I am wondering, does that mean that you changed your idea from your original paper, or what is the reason behind the change? Or are you just trying new ideas?

Also, I was wondering, what is the reasoning behind having `α*μ²` instead of, like in your latest code, a single `σ` value? I've read the paper but failed to understand the logic behind it.

Keep up the good work!

**Comment by kumar-shridhar** [comment]
Hi. 
The main idea for sigma dependance on mu is to first calculate mu and then calculate the deviation from the mu observed (2-time convolution as shown in the paper).

However, better results are observed from taking a single sigma value (as generally used in the VAEs) and hence in the code, the sigma is a single value and the other code is commented out. However, feel free to experiment with sigma.
