### ISSUE TITLE
Could anyone please explain the new kl divergence to me? thx

### ISSUE THREAD

**Issue by lemonahmas** [kumar-shridhar/PyTorch-BayesianCNN#13]
The new way to compute the kl confuses me for a long time, could anyone explain to me the reason for using this equation, please? thanks.
And while training the model with main_bayes.py ,the acc was always 10% using CIFAR10 and 1% using CIFAR100, which I can say is blindly picking, could anyone help?

**Comment by mrivar** [comment]
Regarding the KL calculation: he is basically using the formula explained in this post: https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians
assuming the mu of the prior (μ2) to be zero.
