### ISSUE TITLE
The updated code seems faulty

### ISSUE THREAD

**Issue by pvmolle** [kumar-shridhar/PyTorch-BayesianCNN#14]
The changes introduced by  f41aa32 (updated KL) result in a size mismatch error, e.g. in the `Bayesian_CNN_Detailed` notebook.

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>()

PyTorch-BayesianCNN/Image Recognition/utils/BayesianModels/BayesianAlexNet.py in probforward(self, x)
     42             if hasattr(layer, 'convprobforward') and callable(layer.convprobforward):
     43                 x, _kl, = layer.convprobforward(x)
---> 44                 kl += _kl
     45 
     46             elif hasattr(layer, 'fcprobforward') and callable(layer.fcprobforward):

RuntimeError: The size of tensor a (11) must match the size of tensor b (5) at non-singleton dimension 3
```

Simply summing the `_kl` variable resolves this error. But I am unable to train a model on MNIST, while I was able to get a working MNIST classifier using the previous version of the code (not on CIFAR, though, see #8).

**Comment by lemonahmas** [comment]
I summed up the KL vector, and the accuracy becomes apparently low, 1% using CIFAR100, 10% using CIFAR10, this is blind picking.
KL divergence, in my opinion, should be a summed up value I think. But the result is really bad after 
kl = kl.sum()

**Comment by aadityachapagain** [comment]
Same problem here anybody know how to solve this issue?

**Comment by ClaartjeBarkhof** [comment]
When printing the shape of the KL-divergence it seems to be torch.Size([6, 3, 5, 5]), which seems strange to me. Isn't it supposed to be a scalar?

**Comment by lemonahmas** [comment]
> When printing the shape of the KL-divergence it seems to be torch.Size([6, 3, 5, 5]), which seems strange to me. Isn't it supposed to be a scalar?

Yes, I think they forgot to sum the tensor up and the end, but after I summed it up, the accuracy becomes so low.

**Comment by lemonahmas** [comment]
![image](https://user-images.githubusercontent.com/13514693/59642342-7eb01b00-915c-11e9-86fa-f1f69fd3731d.png)
The accuracy is still very low as you can see from the image above, this result comes from the latest code.

**Comment by kumar-shridhar** [comment]
Sorry for the delayed response. A basic version of the code is fixed and is up and running.
