### ISSUE TITLE
No " Applying two sequential convolutional operations"

### ISSUE THREAD

**Issue by lenz3000** [kumar-shridhar/PyTorch-BayesianCNN#16]
Hi,
I was just looking at your paper and code.
And I don't see any sign of applying the convolutional operation two times, only once here:
https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/d73da93fde64fa93e933f88c90cce54a4d618589/Image%20Recognition/utils/BBBlayers.py#L48

It seems like you did that in earlier versions of your code as in this commented out bit in BBBLayers_.py :
```
        # conv_qw_mean = F.conv2d(input=input, weight=weight, stride=self.stride, padding=self.padding,
        #                              dilation=self.dilation, groups=self.groups)
        # conv_qw_std = torch.sqrt(1e-8 + F.conv2d(input=input.pow(2), weight=torch.exp(self.log_alpha)*weight.pow(2),
        #                                          stride=self.stride, padding=self.padding, dilation=self.dilation, groups=self.groups)) 
```

Why is that?

**Comment by kumar-shridhar** [comment]
Yes, it is applied in the previous code (still there inside utils). However, it takes more time to converge. Hence, another version that is faster and more efficient has been provided that uses just one convolution.

**Comment by ludwigwinkler** [comment]
See ... that's what I told you :D

**Comment by TMullerSG** [comment]
is it true you just revert back to the 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/35680569/67372452-82432b00-f5b0-11e9-95d9-bcdf74cd0a4f.png">which is used in 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/35680569/67372496-938c3780-f5b0-11e9-9bc9-30bb1d23598d.png">

**Comment by kumar-shridhar** [comment]
I would say it is the LRT trick used in the code that works well.
