### ISSUE TITLE
I have no idea why the Superresolution  is Baysian,i think it is normal Conv2d in model.py 

### ISSUE THREAD

**Issue by smallapes** [kumar-shridhar/PyTorch-BayesianCNN#19]
I have no idea why the Superresolution  is Baysian,i think it is normal Conv2d in model.py 
        self.relu = nn.ReLU()
        self.conv1 = nn.Conv2d(1, 64, (5, 5), (1, 1), (2, 2))
        self.conv2 = nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1))
        self.conv3 = nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1))
        self.conv4 = nn.Conv2d(32, upscale_factor ** 2, (3, 3), (1, 1), (1, 1))
        self.pixel_shuffle = nn.PixelShuffle(upscale_factor)

**Comment by kumar-shridhar** [comment]
Hi @smallapes,

Just replace the `nn.Conv2d` with `BBBConv2d` and you will have Bayeisan Conv Layers instead of normal Conv layers. Please check Image Recognition repo for more details.
