### ISSUE TITLE
BBBLayers

### ISSUE THREAD

**Issue by lukealk98** [kumar-shridhar/PyTorch-BayesianCNN#20]
Hi,

BBBLayers_ file has an error at the __init__ methods. I have modified it for my use, but I think it's worth noting (p or q)_logvar_init are non-default variables defined after default variables. (which gives Syntax error.)

Not a big problem anyway - just a small bug :) Might be wrong on my part.

**Comment by kumar-shridhar** [comment]
Hi,

Can you please do a pull request and I will have a look. 
Thanks.

**Comment by Vikram2712** [comment]
Hi, 
when i am trying to import utils.BayesianModels.BayesianAlexNet import BBBAlexNet
then it is showing version issue and no module found. so is there any method to import that library??

**Comment by kumar-shridhar** [comment]
Hi @Vikram2712 ,
Make sure that there is utils/BayesianModels directory and BayesianAlexNet file exists. 
Otherwise, there should be no error. 
Can you also share the exact error you are getting?

**Comment by Vikram2712** [comment]
Actually i am using Google colab so I have to add the directory of utils in
that right for further process.

**Comment by Vikram2712** [comment]
![12](https://user-images.githubusercontent.com/51292503/63228792-fad6e580-c215-11e9-9e50-67903e602b25.PNG)

**Comment by kumar-shridhar** [comment]
Hi @Vikram2712 ,

Did you manage to solve the issue?

**Comment by ak-kat** [comment]
Hi Shridhar,

I have tried to execute Bayesian_CNN_Detailed_.ipynb. In cell 2 got the error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-d99c0fa3da17> in <module>()
----> 1 from utils.BBBlayers import GaussianVariationalInference
      2 from utils.BayesianModels.Bayesian3Conv3FC import BBB3Conv3FC
      3 from utils.BayesianModels.BayesianAlexNet import BBBAlexNet
      4 from utils.BayesianModels.BayesianLeNet import BBBLeNet
      5 from utils.BayesianModels.BayesianSqueezeNet import BBBSqueezeNet

ImportError: cannot import name 'GaussianVariationalInference'

I have changed 1 from utils.BBBlayers import GaussianVariationalInference to 1 from utils.BBBlayers_ import GaussianVariationalInference as BBBlayers doesn't contain GaussianVariationalInference (changed in Bayesian3Conv3FC.py)

Then getting the following error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-15-15085a6ca063> in <module>()
      1 from utils.BBBlayers_ import GaussianVariationalInference
----> 2 from utils.BayesianModels.Bayesian3Conv3FC import BBB3Conv3FC
      3 from utils.BayesianModels.BayesianAlexNet import BBBAlexNet
      4 from utils.BayesianModels.BayesianLeNet import BBBLeNet
      5 from utils.BayesianModels.BayesianSqueezeNet import BBBSqueezeNet

/workspace/ak/PyTorch-BayesianCNN-master/Image Recognition/utils/BayesianModels/Bayesian3Conv3FC.py in <module>()
      1 import torch.nn as nn
----> 2 from utils.BBBlayers_ import BBBConv2d, BBBLinearFactorial, FlattenLayer
      3 
      4 class BBB3Conv3FC(nn.Module):
      5     """
ImportError: cannot import name 'BBBConv2d'

And in exeuting main_Bayes.py:
Traceback (most recent call last):
  File "main_Bayes.py", line 27, in <module>
    from utils.BBBlayers_ import GaussianVariationalInference
  File "/PyTorch-BayesianCNN-master/Image Recognition/utils/BBBlayers_.py", line 29
    def __init__(self, in_channels, out_channels, kernel_size, 
                    ^
SyntaxError: non-default argument follows default argument

Could you please tell how to resolve ?
