### ISSUE TITLE
There is a problem with applying BayesianCNN to image restoration

### ISSUE THREAD

**Issue by GGyan** [kumar-shridhar/PyTorch-BayesianCNN#21]
Hello, I am trying to apply the latest program in the direction of image restoration. The current results do not see the noise problem. However, during the test, I found that the image I wanted was not displayed well. The color of the image has changed and the image details and features have disappeared. Because I simply nested the BBBConv2d related program, the activation function used is relu. I don't know if it is wrong for me. If I change BBBConv2d to nn.Conv2d, my program can get the desired result.
Here are the results I got:
![guogong1](https://user-images.githubusercontent.com/50450546/63005027-4a33b380-beae-11e9-94c6-685054f30111.png)
Original image：
![1gugong](https://user-images.githubusercontent.com/50450546/63005088-66cfeb80-beae-11e9-96d9-e936d955a8f3.png)

**Comment by kumar-shridhar** [comment]
please check with this version. Thanks
