### ISSUE TITLE
Bugs in main_Bayes.py

### ISSUE THREAD

**Issue by jiahaosu** [kumar-shridhar/PyTorch-BayesianCNN#22]
Hello,

I tried to run a Bayesian LeNet5 on MNIST. However, I have difficulties in running the main_Bayes.py. It seems to me there are multiple bugs in the files (Flatten layer is not defined, arguments without defaults are defined after the ones that have defaults, a string is called as functions, etc). Could you let me know how I can call your code properly? 

Best

**Comment by kumar-shridhar** [comment]
Hello @jiahaosu ,

Please run the ipython notebook `Bayesian_CNN_Detailed.ipynb`. Everything works there. If you want to run `LeNet`, please see the `AlexNet` file and it works. Just use the same structure. It should work. 

Kumar
