### ISSUE TITLE
explanation about the code you changed

### ISSUE THREAD

**Issue by ShellingFord221** [kumar-shridhar/PyTorch-BayesianCNN#23]
Hi, could you please give a short explanation about the difference between old version and new version of the code? There are so many parameters in your old codes, especially in BBBlayers.py. I really don't know what does each parameter mean in old codes (e.g. qw_mean, conv_qw_mean, qw_logvar, conv_qw_std), and why should they be deleted in new version.

Thanks!

**Comment by kumar-shridhar** [comment]
Hi,

these parameters are what the name suggests: conv is for convolution and mean and variance means the mean and variance of the distributions for the layers. qw_mean and variance were somehow redundant and we removed them.
