### ISSUE TITLE
Cannot reproduce experiment result

### ISSUE THREAD

**Issue by Cliu2** [kumar-shridhar/PyTorch-BayesianCNN#35]
Hi,

I tried your demo code at 

>[ Image Recognition/Bayesian_CNN_Detailed.ipynb](https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/master/Image%20Recognition/Bayesian_CNN_Detailed.ipynb)

But I cannot reproduce your training results, the accuracy stays around 10% and it seems the model is learning nothing.
![image](https://user-images.githubusercontent.com/21998065/67562688-cde10a80-f751-11e9-8608-9531740e6f8a.png)

Would you please advise what could be the problem? Thanks

**Comment by kumar-shridhar** [comment]
Hey @Cliu2 ,

What dataset did you use?

**Comment by Cliu2** [comment]
@kumar-shridhar Thank you for your reply.

I used the CIFAR10 dataset retrived remotely, following your code in the jupyter notebook.
`train_data = datasets.CIFAR10('data', train=True, download=True, transform=transform)`

I simply copy all the codes in the notebook to a python script file and run it in terminal. So all the settings should be same.

**Comment by arcini** [comment]
I am experiencing the exact same issue. It seems that the network is unable to improve on its prediction accuracy due to some bug. I am going to try to look into it as much as I can, but @kumar-shridhar you should check this out since others have posted similar issues.

**Comment by kumar-shridhar** [comment]
Hi,
Please check with the current version. Things should work fine.
