### ISSUE TITLE
about local reparameterization trick

### ISSUE THREAD

**Issue by ShellingFord221** [kumar-shridhar/PyTorch-BayesianCNN#37]
Hi, in your new code, there is no implementation about the local reparameterization trick. If I want to use it to compute the output of the convolution layer, I should replace sigma^2 with alpha * mu^2 (just like the implementation in your old code). But should I also replace sigma^2 with alpha * mu^2 when computing the KL divergence? i.e. should KL also be affected by the parameter alpha? Why or why not? Thanks!

**Comment by fettay** [comment]
Up

**Comment by kumar-shridhar** [comment]
It should. Please check it out now.
