### ISSUE TITLE
regarding softplus function 

### ISSUE THREAD

**Issue by Vikram2712** [kumar-shridhar/PyTorch-BayesianCNN#38]
Hi, 
you have applied softplus function in only standard deviation, will you please explain the reason for that. and  also how to apply reparameterization trick for finding the variance value in simple words. because i didn't able to understand it through your paper.

thanks in advance

**Comment by kumar-shridhar** [comment]
Please check out the [blog](https://towardsdatascience.com/what-uncertainties-tell-you-in-bayesian-neural-networks-6fbd5f85648e) about the paper. I hope it will be more clear.
