### ISSUE TITLE
About BBBlayers

### ISSUE THREAD

**Issue by Cherishyt** [kumar-shridhar/PyTorch-BayesianCNN#39]

**Comment by Cherishyt** [comment]
There is some bug in BBBlayers.py. What is the initial value of p_logvar_init and q_logvar_init? They can't be set None.

**Comment by kumar-shridhar** [comment]
Hi,
The values are initialized inside the Network (like AlexNet). Link [here](https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/master/Image%20Recognition/utils/BayesianModels/BayesianAlexNet.py#L16).

**Comment by Cherishyt** [comment]
Thanks! But the values haven't been initialized in LeNet [code](https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/master/Image%20Recognition/utils/BayesianModels/BayesianLeNet.py). Is it the same as in AlexNet?

**Comment by kumar-shridhar** [comment]
For now please make the LeNet code similar to AlexNet and it will work.
