### ISSUE TITLE
GaussianVariationalInference imported from BBBlayers but defined in BBBlayers_

### ISSUE THREAD

**Issue by EvenStrangest** [kumar-shridhar/PyTorch-BayesianCNN#40]
How come?

**Comment by kumar-shridhar** [comment]
Please use the[ Jupyter Notebook](https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/master/Image%20Recognition/Bayesian_CNN_Detailed.ipynb). It is commented there and ELBO is defined.
