### ISSUE TITLE
BayesianCNN for SuperResolution

### ISSUE THREAD

**Issue by theonegis** [kumar-shridhar/PyTorch-BayesianCNN#41]
Hi, it seems to me there is no Bayesian related code in your SupreResolution implementation, just a regular CNN. What do I miss here? Could you please give me a hint? Many thanks!

**Comment by kumar-shridhar** [comment]
Hi,
The layers used are Bayesian Layers instead of regular ones.

**Comment by theonegis** [comment]
![image](https://user-images.githubusercontent.com/26246669/72400705-13c3d280-3785-11ea-8d7b-eeb251644ff0.png)
These are just regular Conv2D layers from PyTorch, not Bayesian Layers.

**Comment by theonegis** [comment]
I do find a Bayesian version from your another repository [PyTorch-Bayesian-Super-Resolution](https://github.com/kumar-shridhar/PyTorch-Bayesian-Super-Resolution), but the results are not good. Why does the Bayesian CNN version perform not good as the regular CNN?

**Comment by kumar-shridhar** [comment]
Bayesian CNN keeps an account of model uncertainty and for uncertain predictions, the results are not good when making an image super-resolution. There remains some blurriness in the borders.
