### ISSUE TITLE
Python package restructuring

### ISSUE THREAD

**Issue by vakker** [kumar-shridhar/PyTorch-BayesianCNN#44]
It would be great if this was an actual Python package that can be installed with `pip install -e .`
It would require some restructuring and a `setup.py`, but no code changes.
I don't know if it's something you wanted to do, but it would be beneficial for people using the library.

**Comment by kumar-shridhar** [comment]
Hi @vakker ,

We are making some final changes to the repo. Some measures about uncertainty estimation and a different initialization for the layers. It will take 2 weeks overall. After that, we will definitely put things inside a python package. Thanks for notifying us.
