### ISSUE TITLE
num_ens

### ISSUE THREAD

**Issue by Valensic** [kumar-shridhar/PyTorch-BayesianCNN#53]
Hi, I'm trying to apply you framework to a regression problem.
in your default configuration file the `num_ens` variable is set to 1. 
I was reasoning about its influence in the training, since it is the number of samples to estimate the objective function.

Which is the optimal value for this parameter? I couldn't find any discussion about it in the paper!
Thanks for help!

**Comment by kumar-shridhar** [comment]
Hi @Valensic,

We got good results for ```num_ens``` in the range of 5-20.  10 is a good number to start with. Not much difference when the values are higher.

**Comment by Valensic** [comment]
Thank you
