### ISSUE TITLE
Difference between Normal and Normalout ?

### ISSUE THREAD

**Issue by homaralex** [kumar-shridhar/PyTorch-BayesianCNN#6]
What is the difference between the `Normal` and `Normalout` classes (in [utils/BBBdistributions.py](https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/master/Image%20Recognition/utils/BBBdistributions.py) )? They seem to have identical code, but it is confusing.

**Comment by kumar-shridhar** [comment]
There is no difference. It has now been fixed.
