### ISSUE TITLE
[Question] Regression

### ISSUE THREAD

**Issue by luca310795** [kumar-shridhar/PyTorch-BayesianCNN#9]
How should I modify the code to apply it to regression instead of classification? Is it enough to put one output neuron and to change CrossEntropyLoss to MSELoss?

**Comment by kumar-shridhar** [comment]
Yes that should be it.

**Comment by aunsid** [comment]
I haven't been to replicate regression. I am trying to replicate the results from this [post](https://www.ritchievink.com/blog/2019/09/16/variational-inference-from-scratch/) But it seems you have used `criterion = metrics.ELBO() ` and not `CrossEntropyLoss()`

Am I missing something?
